language: generic
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq

branches:
  only:
    - master
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

script:
  - bash appimage/build-plugin.sh
  - bash appimage/build-python.sh python3
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh

after_success:
  - bash upload.sh appimage/*.AppImage
